### ISSUE TITLE
Issue with hovering on the right-section of the tree.

### ISSUE THREAD

**Issue by DineshKarri443** [ssthouse/vue-tree-chart#34] opened 2021-06-10 20:37 UTC
@ssthouse  Sorry for creating another issue. I was not sure if you've gone through my comment in the previous issue. 

I ran into an issue as soon as I added a "link hover" css property. I just added the link hover property to highlight a link when it is hovered. But I observed that only the links in the left-half of the chart are being highlighted. The hover action on the right-half of the chart is not working. Do you know any reason why this might be happening?

I just added a simple hover pseudo-selector to the link tag and changed it to color "red" on hover. You can see the issue in the codesandbox below:

https://codesandbox.io/s/loving-lake-3e6p8?file=/src/components/treeview.vue

![image](https://user-images.githubusercontent.com/68352790/121593519-ab505200-ca59-11eb-8c7e-2ce6432827b6.png)

**Comment by ssthouse** [comment] 2021-06-14 01:01
Hi, sorry for the late reply.

This issue is caused by the dom layer problem. the link between `1` and `3` is blocked.
As you can see in the dom tree, the `dom(<div/>)` has a higher z-index than `<svg/>`.

![image](https://user-images.githubusercontent.com/10973821/121827485-c1c30b80-ccee-11eb-8724-79ee2ff73636.png)


this can be fixed by adjusting `pointer-events` property. I'll fix this ASAP~

**Comment by ssthouse** [comment] 2021-06-14 01:34
@DineshKarri443 hi, this issue has been fixed in `v0.5.3` ~

**Comment by DineshKarri443** [comment] 2021-06-14 03:34
@ssthouse  my bad, I was adding pointer-events: none to dom-container thinking this is overlapping the container and was expecting it to work. Thank you very much for such a prompt fix.

**Closed** 2021-06-14 03:35 UTC
